= Proxier
:toc: left
:toclevels: 3

Simple CLI application to ease the burden of changing proxy settings in files.

== About

I am a little tired of constantly changing proxy settings in Ubuntu files:

. /etc/environment
. /etc/apt/apt.conf.d/proxy.conf

So, in order to learn GOlang and make something useful - here we have this app.

== Usage

Just call appropriate command to achieve your goal.
[source, bash]
----
If you are lazy bastard, as I am, this application will enable/disable proxy in certain files in Linux.

What you need to do:
1. Create config.json (you can create template one with command config --template)
2. Call application with cmd 'set' (or 'unset').
By defaults application will create backup files in subdirectory backup/.

Usage:
  proxier [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  config      Allows modification of config.json file via cli
  help        Help about any command
  set         Configure files to use proxy
  unset       Configure files to NOT USE proxy

Flags:
  -b, --backup    make backup of files, which will be overridden (default true)
  -h, --help      help for proxier
  -v, --verbose   make an application full of logs

Use "proxier [command] --help" for more information about a command.


----
== Configuration

It supports configuration via `config.json`
Will be easier to provide example config, then to explain:
[source, json]
----
{
    "settings": {
        "https_proxy": "\"https://${user}:${password}@${server}:${port}\"",
        "password": "password",
        "port": "80",
        "server": "192.168.0.100",
        "user": "user"
    },
    "files": [
        {
            "name": "/location/of/file",
            "append": [
                "HTTP_PROXY=${http_proxy}"
            ],
            "remove": [
                "HTTP_PROXY"
            ]
        },
        {
            "name": "/location/of/second/file",
            "append": [
                "Acquire::http::proxy ${http_proxy}",
                "Acquire::https::proxy ${http_proxy}"
            ],
            "remove": [
                "Acquire"
            ]
        },
    ]
}
----

There are two main sections `settings` and `files`.
In `settings` you can provide anything - it doesn't demand any special keys.
In `files` application expect to have an array of files. Every file need to have:

. name - file to be modified,
. append - an array of lines, which will be appended to contents of specified file,
. remove - an array of patterns, which will be removed from contents of specified file

=== Substitution

Config file supports substitution of values with `${name}` syntax.
If  `${name}` will be found wherever in json, it will get replaced with value of `name` key.
You can find an example in config above.

=== Template configuration file

You can create template config file with command:

[source, bash]
----
go run main.go config --template
----








